// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD0tk7oddLptPoPqK8dpnQJNSh8ZVLmMdk',
    appId: '1:132985607801:web:bdd6ee6f6c95e6802666a8',
    messagingSenderId: '132985607801',
    projectId: 'finmob-c3ef3',
    authDomain: 'finmob-c3ef3.firebaseapp.com',
    storageBucket: 'finmob-c3ef3.firebasestorage.app',
    measurementId: 'G-4WQMNT9Q0S',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyApMqPPnLytUC1nHNBZJ2rgqkkedeAYfsU',
    appId: '1:132985607801:android:e1d41a2dfe3015342666a8',
    messagingSenderId: '132985607801',
    projectId: 'finmob-c3ef3',
    storageBucket: 'finmob-c3ef3.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDloJ8XifjkcC2EUHM4MFi1xADkKMlBf5g',
    appId: '1:132985607801:ios:8405fb381864f5132666a8',
    messagingSenderId: '132985607801',
    projectId: 'finmob-c3ef3',
    storageBucket: 'finmob-c3ef3.firebasestorage.app',
    iosBundleId: 'com.example.mobile',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDloJ8XifjkcC2EUHM4MFi1xADkKMlBf5g',
    appId: '1:132985607801:ios:8405fb381864f5132666a8',
    messagingSenderId: '132985607801',
    projectId: 'finmob-c3ef3',
    storageBucket: 'finmob-c3ef3.firebasestorage.app',
    iosBundleId: 'com.example.mobile',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD0tk7oddLptPoPqK8dpnQJNSh8ZVLmMdk',
    appId: '1:132985607801:web:d565bf6668bff08f2666a8',
    messagingSenderId: '132985607801',
    projectId: 'finmob-c3ef3',
    authDomain: 'finmob-c3ef3.firebaseapp.com',
    storageBucket: 'finmob-c3ef3.firebasestorage.app',
    measurementId: 'G-DJ8HLX0Y9P',
  );
}
